// packages/lang-react/src/Renderer.tsx
import React, { Component, Fragment, useEffect } from "react";
import { OpenUIContext, useOpenUI, useRenderNode } from "./context";
import { useOpenUIState } from "./hooks/useOpenUIState";
import type { ComponentRenderer, Library } from "./library";
import type { ActionEvent, ElementNode, ParseResult } from "./parser/types";

export interface RendererProps {
  /** Raw response text (openui-lang code, possibly with <context> tag). */
  response: string | null;
  /** Component library from createLibrary(). */
  library: Library;
  /** Whether the LLM is still streaming (form interactions disabled during streaming). */
  isStreaming?: boolean;
  /** Callback when a component triggers an action. */
  onAction?: (event: ActionEvent) => void;
  /** Persist message content with form state on field change. */
  updateMessage?: (message: string) => void;
  /** Called whenever the parse result changes. */
  onParseResult?: (result: ParseResult | null) => void;
}

// ─── Error boundary ───

interface ErrorBoundaryProps {
  children: React.ReactNode;
}

interface ErrorBoundaryState {
  hasError: boolean;
}

class ElementErrorBoundary extends Component<ErrorBoundaryProps, ErrorBoundaryState> {
  private lastValidChildren: React.ReactNode = null;

  constructor(props: ErrorBoundaryProps) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(): ErrorBoundaryState {
    return { hasError: true };
  }

  componentDidMount(): void {
    if (!this.state.hasError) {
      this.lastValidChildren = this.props.children;
    }
  }

  componentDidUpdate(prevProps: ErrorBoundaryProps): void {
    if (!this.state.hasError) {
      this.lastValidChildren = this.props.children;
    }
    if (this.state.hasError && prevProps.children !== this.props.children) {
      this.setState({ hasError: false });
    }
  }

  componentDidCatch(error: Error, info: React.ErrorInfo): void {
    console.error("[openui] Component render error:", error, info);
  }

  render() {
    if (this.state.hasError) {
      return this.lastValidChildren;
    }
    return this.props.children;
  }
}

// ─── Internal rendering ───

/**
 * Recursively renders a parsed value (element, array, primitive)
 * into React nodes.
 */
function renderDeep(value: unknown): React.ReactNode {
  if (value == null) return null;
  if (typeof value === "string") return value;
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return String(value);

  if (Array.isArray(value)) {
    return value.map((v, i) => <Fragment key={i}>{renderDeep(v)}</Fragment>);
  }

  if (typeof value === "object" && value !== null) {
    const obj = value as Record<string, unknown>;
    if (obj.type === "element") {
      return <RenderNode node={obj as unknown as ElementNode} />;
    }
  }

  return null;
}

/**
 * Renders a single ElementNode.
 */
function RenderNode({ node }: { node: ElementNode }) {
  const { library } = useOpenUI();
  const Comp = library.components[node.typeName]?.component;

  if (!Comp) return null;

  return (
    <ElementErrorBoundary>
      <RenderNodeInner el={node} Comp={Comp} />
    </ElementErrorBoundary>
  );
}

/**
 * Renders a resolved element using its renderer. Gets renderNode from context.
 */
function RenderNodeInner({ el, Comp }: { el: ElementNode; Comp: ComponentRenderer<any> }) {
  const renderNode = useRenderNode();
  return <Comp props={el.props} renderNode={renderNode} />;
}

// ─── Public component ───

export function Renderer({
  response,
  library,
  isStreaming = false,
  onAction,
  updateMessage,
  onParseResult,
}: RendererProps) {
  const { result, contextValue } = useOpenUIState(
    {
      response,
      library,
      isStreaming,
      onAction,
      updateMessage,
    },
    renderDeep,
  );

  useEffect(() => {
    onParseResult?.(result);
  }, [result, onParseResult]);

  if (!result?.root) {
    return null;
  }

  return (
    <OpenUIContext.Provider value={contextValue}>
      <RenderNode node={result.root} />
    </OpenUIContext.Provider>
  );
}

// packages/vue-lang/src/Renderer.vue
<script setup lang="ts">
import type {
  ActionEvent,
  ElementNode,
  ParseResult,
  OpenUIError,
  McpClientLike,
  ToolProvider,
} from "@openuidev/lang-core";
import { BuiltinActionType, extractToolResult, ToolNotFoundError } from "@openuidev/lang-core";
import { computed, h, toRef, watch, type Component, type VNode } from "vue";
import { provideOpenUIContext } from "./context.js";
import type { Library, RenderNodeResult } from "./library.js";
import RenderNode from "./RenderNode.vue";
import { useOpenUIState } from "./state.js";

interface RendererProps {
  /** Raw response text (openui-lang code). */
  response: string | null;
  /** Component library from createLibrary(). */
  library: Library;
  /** Whether the LLM is still streaming (form interactions disabled during streaming). */
  isStreaming?: boolean;
  /** Callback when a component triggers an action. */
  onAction?: (event: ActionEvent) => void;
  /**
   * Called whenever a form field value changes. Receives the raw form state map.
   * The consumer decides how to persist this (e.g. embed in message, store separately).
   */
  onStateUpdate?: (state: Record<string, any>) => void;
  /**
   * Initial form state to hydrate on load (e.g. from a previously persisted message).
   * Shape: { formName: { fieldName: { value, componentType } } }
   */
  initialState?: Record<string, any>;
  /** Called whenever the parse result changes. */
  onParseResult?: (result: ParseResult | null) => void;
  /** Tool provider for Query()/Mutation() calls. */
  toolProvider?:
    | Record<string, (args: Record<string, unknown>) => Promise<unknown>>
    | McpClientLike
    | null;
  /** Custom loading indicator shown while queries are fetching. */
  queryLoader?: Component | VNode | null;
  /** Called with structured errors. */
  onError?: (errors: OpenUIError[]) => void;
}

const props = withDefaults(defineProps<RendererProps>(), {
  isStreaming: false,
});

// Stable ToolProvider wrapper — identity never changes. callTool() reads the
// latest input from props.toolProvider on every call, so function map updates
// are always observed without triggering re-creation.
const stableToolProvider: ToolProvider = {
  async callTool(toolName: string, args: Record<string, unknown>): Promise<unknown> {
    const current = props.toolProvider;
    if (current == null) throw new Error("[openui] toolProvider is null");
    if (typeof (current as any).callTool === "function") {
      const result = await (current as any).callTool({
        name: toolName,
        arguments: args,
      });
      return extractToolResult(result);
    }
    const map = current as Record<string, (a: Record<string, unknown>) => Promise<unknown>>;
    const fn = map[toolName];
    if (!fn) throw new ToolNotFoundError(toolName, Object.keys(map));
    return fn(args);
  },
};

const resolvedToolProvider = computed<ToolProvider | null>(() => {
  return props.toolProvider != null ? stableToolProvider : null;
});

// ─── Render node function ───
function renderNode(value: unknown): RenderNodeResult {
  if (value == null) return null;
  if (typeof value === "string") return value;
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (Array.isArray(value)) {
    return value.flatMap((item) => {
      const result = renderNode(item);
      return Array.isArray(result) ? result : [result];
    });
  }
  if (typeof value === "object" && (value as any).type === "element") {
    return h(RenderNode, { node: value as ElementNode });
  }
  return null;
}

const { result, parseResult, contextValue, isQueryLoading } = useOpenUIState(
  {
    response: toRef(props, "response"),
    library: props.library,
    isStreaming: toRef(props, "isStreaming"),
    onAction: (e) => props.onAction?.(e),
    onStateUpdate: (s) => props.onStateUpdate?.(s),
    initialState: props.initialState,
    toolProvider: resolvedToolProvider,
    onError: (errs) => props.onError?.(errs),
  },
  renderNode,
);

// ─── Notify on parse result change ───
watch(
  parseResult,
  (r) => {
    props.onParseResult?.(r);
  },
  { immediate: true },
);

// ─── Provide context ───
provideOpenUIContext(contextValue.value);
</script>

<template>
  <div style="position: relative">
    <div v-if="isQueryLoading" style="position: absolute; top: 8px; right: 8px; z-index: 10">
      <component v-if="props.queryLoader" :is="props.queryLoader" />
      <div
        v-else
        style="
          width: 16px;
          height: 16px;
          border: 2px solid #e5e7eb;
          border-top-color: #3b82f6;
          border-radius: 50%;
          animation: openui-spin 0.6s linear infinite;
        "
      />
    </div>
    <div :style="{ opacity: isQueryLoading ? 0.7 : 1, transition: 'opacity 0.2s ease' }">
      <RenderNode v-if="result?.root" :node="result.root" />
    </div>
  </div>
</template>

<style>
@keyframes openui-spin {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
</style>
